### ISSUE TITLE
bot.py just exists

### ISSUE THREAD

**Issue by ufa** [asdofindia/python-telegram-bot#1]
Hello,
I am trying to use python-telegram-bot, but I am having issues on new telegram-cli.
I had to change the paths and added a '-cli' in program call.
But when I do python bot.py, nothing happens:

$python bot.py
Telegram-cli version 1.0.5, Copyright (C) 2013-2014 Vitaly Valtman
Telegram-cli comes with ABSOLUTELY NO WARRANTY; for details type `show_license'.
This is free software, and you are welcome to redistribute it
under certain conditions; type`show_license' for details.
 **\* No pubic keys found
$

it seems to me that the program just leave Telegram. 
Any help will be appreciated

**Comment by asdofindia** [comment]
tg-cli seems to have had a few changes recently (after being silent for months)
"-cli" addition seems to be necessary. You're right.

Can you please check the tg-cli independently and make sure it is working? (You're probably missing the public key file)
Run the bot after that.

**Comment by ufa** [comment]
It worked, thanks. 
But I was looking for a chatty bot. Is it easy to add some random responses?

**Comment by asdofindia** [comment]
Yes, checkout https://github.com/asdofindia/python-whatsapp-bot/blob/master/modules/chatterbotapi.py

**Comment by ufa** [comment]
Should I call it inside bot.py?

**Comment by ufa** [comment]
I have imported it in bot.py. No erros, but no chat :(
How can I call the classes from chatterbotapi in bot.py?

**Comment by asdofindia** [comment]
https://github.com/asdofindia/python-whatsapp-bot/blob/master/modules/elizaloader.py

You'll need something like:

```
from modules.chatterbotapi import ChatterBotFactory, ChatterBotType
factory = ChatterBotFactory()
bot = factory.create(ChatterBotType.PANDORABOTS, 'b0dafd24ee35a477')
botsession = bot.create_session()
reply=botsession.think(query)
```

And then you'll need to clean the html tags out depending.

**Comment by ufa** [comment]
$ python bot.py

Traceback (most recent call last):
  File "bot.py", line 17, in <module>
    reply=botsession.think(query)
NameError: name 'query' is not defined

I saw that in google.py, there is a query def, but it does not work :(

**Comment by asdofindia** [comment]
Well, query is the message you want to send.
try 

```
botsession.think("Hi there!")
```

or

```
query=message
```

**Comment by ufa** [comment]
It didn't work, but thank you anyway.
Can we hope for a future integrated chatty version?
Keep rocking :)

**Comment by asdofindia** [comment]
I just pushed a new version ;)

**Comment by ufa** [comment]
"made a chatty bot on request by ufa" :dancers:

**Comment by ufa** [comment]
On line 129 in bot.py:
    proc=subprocess.Popen([pathtotg+'bin/telegram','-k',pathtotg+'tg-server.pub'],stdin=subprocess.PIPE,stdout=subprocess.PIPE)

Have to add telegram-cli instead of just telegram. Small change. So it will be:

```
proc=subprocess.Popen([pathtotg+'bin/telegram-cli','-k',pathtotg+'tg-server.pub'],stdin=subprocess.PIPE,stdout=subprocess.PIPE)
```

**Comment by asdofindia** [comment]
Oh yeah, I had almost fixed it :P
Do you want to create a pull request?

**Comment by ufa** [comment]
I tried, but I cannot manage github well :(

**Comment by asdofindia** [comment]
It's fine. I've pushed it. Thanks for noting.

**Comment by ufa** [comment]
Thanks for the excellent bot :smile:
