### ISSUE TITLE
Long message

### ISSUE THREAD

**Issue by vavoluk** [asdofindia/python-telegram-bot#6]
I can't send long messages.
How to autosplit messages?

**Comment by asdofindia** [comment]
I don't understand. The tg-cli should take care of sending messages of any length. I think the bot writes to a text file and uses that to send lines.

**Comment by vavoluk** [comment]
Yes, bot writes to a text file.
But now I can't receive message when my text file is so big.

In bot logs it seems like

> send_text Test Account temp

$ wc -c temp 
14269 temp

When my text file small I've got message without problems.

**Comment by asdofindia** [comment]
Well, try sending that message using the tg-cli manually. Does it work?

**Comment by vavoluk** [comment]
No, after pushing enter nothing happens.

**Comment by asdofindia** [comment]
In that case, it's a problem with tg-cli, I think.

**Comment by vavoluk** [comment]
Yep! Thats why I think about splitting messages.
It is possible to split messages in bot?
